import logging

# playwright logging level
GERAPY_PLAYWRIGHT_LOGGING_LEVEL = "DEBUG"

# playwright timeout
GERAPY_PLAYWRIGHT_DOWNLOAD_TIMEOUT = 30

# playwright browser window
# GERAPY_PLAYWRIGHT_WINDOW_WIDTH = 1400
# GERAPY_PLAYWRIGHT_WINDOW_HEIGHT = 700

# playwright settings
# GERAPY_PLAYWRIGHT_HEADLESS = True
# GERAPY_PLAYWRIGHT_EXECUTABLE_PATH = None
# GERAPY_PLAYWRIGHT_IGNORE_HTTPS_ERRORS = False
# GERAPY_PLAYWRIGHT_PRETEND = True

# playwright args
# GERAPY_PLAYWRIGHT_DISABLE_EXTENSIONS = True
# GERAPY_PLAYWRIGHT_HIDE_SCROLLBARS = True
GERAPY_PLAYWRIGHT_MUTE_AUDIO = True
# GERAPY_PLAYWRIGHT_NO_SANDBOX = True
# GERAPY_PLAYWRIGHT_DISABLE_SETUID_SANDBOX = True
# GERAPY_PLAYWRIGHT_DISABLE_GPU = True

# GERAPY_PLAYWRIGHT_SCREENSHOT = None
GERAPY_PLAYWRIGHT_SLEEP = 1

# delay by load page
AFTER_PAGE_LOAD_DELAY = 3

# playwright host list
GERAPY_PLAYWRIGHT_HOST_LIST = ["172.17.255.227:9001","172.17.255.227:9001"]


